USE interviewtwin;

CREATE TABLE IF NOT EXISTS aptitude_questions (
    aptitude_id BIGINT AUTO_INCREMENT PRIMARY KEY,

    title VARCHAR(255) NOT NULL UNIQUE,
    question_text TEXT NOT NULL,
    problem_statement TEXT NOT NULL,

    question_type VARCHAR(50) NOT NULL DEFAULT 'APTITUDE',
    category VARCHAR(100) NOT NULL,
    difficulty_level VARCHAR(20) NOT NULL,
    blooms_level VARCHAR(30),

    description TEXT,
    constraints TEXT,
    input_format TEXT,
    output_format TEXT,

    options JSON,
    correct_answer VARCHAR(255) NOT NULL,
    explanation TEXT,
    hints JSON,
    tags JSON,

    acceptance_rate DECIMAL(5,2) DEFAULT 0.00,
    total_attempts INT DEFAULT 0,
    total_correct INT DEFAULT 0,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
USE interviewtwin;

INSERT IGNORE INTO aptitude_questions
(
    title,
    question_text,
    problem_statement,
    question_type,
    category,
    difficulty_level,
    blooms_level,
    description,
    constraints,
    input_format,
    output_format,
    options,
    correct_answer,
    explanation,
    hints,
    tags,
    acceptance_rate,
    total_attempts,
    total_correct
)
VALUES

-- =========================
-- PERCENTAGES
-- =========================

(
    'Percentage Increase',
    'A number is increased from 200 to 240. What is the percentage increase?',
    'Find the percentage by which the original number increased.',
    'APTITUDE',
    'Percentages',
    'EASY',
    'APPLY',
    'Calculate percentage increase using the difference divided by the original value.',
    'Original value = 200, New value = 240',
    'Original value and new value',
    'Percentage increase',
    '["10%","15%","20%","25%"]',
    '20%',
    'Increase = 240 - 200 = 40. Percentage increase = (40/200) × 100 = 20%.',
    '["Percentage increase = (Increase / Original) × 100"]',
    '["percentage","basic-math"]',
    90.0, 0, 0
),

(
    'Percentage Decrease',
    'A price decreases from 500 to 425. What is the percentage decrease?',
    'Find the percentage decrease from the original price.',
    'APTITUDE',
    'Percentages',
    'EASY',
    'APPLY',
    'Compare the decrease with the original price.',
    'Original price = 500, New price = 425',
    'Original and new price',
    'Percentage decrease',
    '["10%","12%","15%","20%"]',
    '15%',
    'Decrease = 500 - 425 = 75. Percentage decrease = (75/500) × 100 = 15%.',
    '["Use original value as the denominator."]',
    '["percentage","decrease"]',
    88.0, 0, 0
),

(
    'Percentage of a Number',
    'What is 25% of 480?',
    'Calculate the given percentage of the number.',
    'APTITUDE',
    'Percentages',
    'EASY',
    'APPLY',
    'Convert the percentage into a fraction and multiply.',
    'Number = 480',
    'A percentage and a number',
    'Calculated value',
    '["100","110","120","125"]',
    '120',
    '25% = 25/100 = 1/4. Therefore, 480/4 = 120.',
    '["25% is equal to one-fourth."]',
    '["percentage","arithmetic"]',
    94.0, 0, 0
),

(
    'Successive Percentage Increase',
    'A salary of 20000 is increased by 10% and then by another 20%. What is the final salary?',
    'Calculate the result of two successive percentage increases.',
    'APTITUDE',
    'Percentages',
    'MEDIUM',
    'ANALYZE',
    'Apply each percentage increase to the updated value.',
    'Initial salary = 20000',
    'Initial salary and percentage increases',
    'Final salary',
    '["24000","26000","26400","26800"]',
    '26400',
    'After 10% increase: 22000. After 20% increase: 22000 × 1.20 = 26400.',
    '["Do not add the percentages directly. Apply them successively."]',
    '["percentage","successive-percentage"]',
    79.0, 0, 0
),

(
    'Percentage Change in Value',
    'A number is first increased by 20% and then decreased by 20%. What is the overall percentage change?',
    'Determine the net percentage change after two successive changes.',
    'APTITUDE',
    'Percentages',
    'MEDIUM',
    'ANALYZE',
    'Use a convenient base value such as 100.',
    'Initial value = 100',
    'Initial value and two percentage changes',
    'Overall percentage change',
    '["0%","2% decrease","4% decrease","4% increase"]',
    '4% decrease',
    'Take 100. After 20% increase it becomes 120. A 20% decrease gives 96. Therefore the net decrease is 4%.',
    '["Always apply the second percentage to the changed value."]',
    '["percentage","successive-change"]',
    82.0, 0, 0
),

-- =========================
-- PROFIT AND LOSS
-- =========================

(
    'Basic Profit Percentage',
    'An article is bought for 500 and sold for 600. What is the profit percentage?',
    'Find the percentage profit on the cost price.',
    'APTITUDE',
    'Profit and Loss',
    'EASY',
    'APPLY',
    'Calculate profit and express it as a percentage of cost price.',
    'Cost price = 500, Selling price = 600',
    'Cost price and selling price',
    'Profit percentage',
    '["10%","15%","20%","25%"]',
    '20%',
    'Profit = 600 - 500 = 100. Profit percentage = (100/500) × 100 = 20%.',
    '["Profit = SP - CP"]',
    '["profit","loss","percentage"]',
    91.0, 0, 0
),

(
    'Basic Loss Percentage',
    'An article costing 800 is sold for 680. What is the loss percentage?',
    'Calculate the loss as a percentage of cost price.',
    'APTITUDE',
    'Profit and Loss',
    'EASY',
    'APPLY',
    'Find the difference between cost price and selling price.',
    'Cost price = 800, Selling price = 680',
    'Cost price and selling price',
    'Loss percentage',
    '["10%","12%","15%","20%"]',
    '15%',
    'Loss = 800 - 680 = 120. Loss percentage = (120/800) × 100 = 15%.',
    '["Loss percentage = (Loss / CP) × 100"]',
    '["profit","loss"]',
    89.0, 0, 0
),

(
    'Find Selling Price from Profit',
    'An article costs 1200. If the profit is 25%, what is its selling price?',
    'Find the selling price when cost price and profit percentage are known.',
    'APTITUDE',
    'Profit and Loss',
    'EASY',
    'APPLY',
    'Calculate profit and add it to the cost price.',
    'CP = 1200, Profit = 25%',
    'Cost price and profit percentage',
    'Selling price',
    '["1350","1450","1500","1550"]',
    '1500',
    'Profit = 25% of 1200 = 300. Selling price = 1200 + 300 = 1500.',
    '["SP = CP + Profit"]',
    '["profit","selling-price"]',
    87.0, 0, 0
),

(
    'Discount Calculation',
    'A shirt marked at 2000 is sold at a discount of 15%. What is the selling price?',
    'Calculate the selling price after applying the discount.',
    'APTITUDE',
    'Profit and Loss',
    'EASY',
    'APPLY',
    'Calculate the discount and subtract it from the marked price.',
    'Marked price = 2000, Discount = 15%',
    'Marked price and discount percentage',
    'Selling price',
    '["1600","1650","1700","1750"]',
    '1700',
    'Discount = 15% of 2000 = 300. Selling price = 2000 - 300 = 1700.',
    '["SP after discount = MP - Discount"]',
    '["discount","profit-loss"]',
    92.0, 0, 0
),

(
    'Profit After Discount',
    'An article costs 1000 and is marked at 1500. If a discount of 10% is given, what is the profit percentage?',
    'Find the actual selling price after discount and calculate the profit percentage.',
    'APTITUDE',
    'Profit and Loss',
    'MEDIUM',
    'ANALYZE',
    'Apply the discount to the marked price before calculating profit.',
    'CP = 1000, MP = 1500, Discount = 10%',
    'Cost price, marked price, discount',
    'Profit percentage',
    '["25%","30%","35%","40%"]',
    '35%',
    'Selling price = 1500 - 150 = 1350. Profit = 350. Profit percentage = 35%.',
    '["First find SP after discount. Then compare SP with CP."]',
    '["profit","discount","percentage"]',
    76.0, 0, 0
),

-- =========================
-- RATIO AND PROPORTION
-- =========================

(
    'Simple Ratio',
    'The ratio of boys to girls in a class is 3:2. If there are 30 boys, how many girls are there?',
    'Use the given ratio to calculate the number of girls.',
    'APTITUDE',
    'Ratio and Proportion',
    'EASY',
    'APPLY',
    'Find the multiplication factor from the known part.',
    'Boys : Girls = 3 : 2',
    'Ratio and known quantity',
    'Number of girls',
    '["15","20","25","30"]',
    '20',
    '3 parts correspond to 30, so one part = 10. Girls = 2 × 10 = 20.',
    '["Divide the known quantity by its ratio part."]',
    '["ratio","proportion"]',
    93.0, 0, 0
),

(
    'Simplify Ratio',
    'Simplify the ratio 48:72.',
    'Express the given ratio in its simplest form.',
    'APTITUDE',
    'Ratio and Proportion',
    'EASY',
    'APPLY',
    'Divide both terms by their greatest common divisor.',
    'Both values are positive integers.',
    'Two integers',
    'Simplified ratio',
    '["2:3","3:4","4:5","5:6"]',
    '2:3',
    'The GCD of 48 and 72 is 24. Dividing both by 24 gives 2:3.',
    '["Find the GCD of both terms."]',
    '["ratio","gcd","simplification"]',
    95.0, 0, 0
),

(
    'Divide Amount in Ratio',
    'Divide 900 between A and B in the ratio 4:5. How much does B receive?',
    'Distribute the total amount according to the given ratio.',
    'APTITUDE',
    'Ratio and Proportion',
    'EASY',
    'APPLY',
    'Find the value of one ratio part and multiply by B’s share.',
    'Total = 900, Ratio = 4:5',
    'Total amount and ratio',
    'Amount received by B',
    '["400","450","500","550"]',
    '500',
    'Total parts = 9. One part = 900/9 = 100. B receives 5 × 100 = 500.',
    '["Add the ratio parts first."]',
    '["ratio","division"]',
    91.0, 0, 0
),

(
    'Direct Proportion',
    'If 5 books cost 400, what is the cost of 8 books at the same rate?',
    'Use direct proportion to find the cost of a different number of books.',
    'APTITUDE',
    'Ratio and Proportion',
    'EASY',
    'APPLY',
    'Find the cost per book and multiply by the required quantity.',
    'Cost is directly proportional to quantity.',
    'Known quantity and cost, required quantity',
    'Required cost',
    '["560","600","640","680"]',
    '640',
    'Cost per book = 400/5 = 80. Cost of 8 books = 8 × 80 = 640.',
    '["In direct proportion, more quantity means more cost."]',
    '["ratio","proportion","unitary-method"]',
    90.0, 0, 0
),

(
    'Ratio with Three Quantities',
    'The ratio of three numbers is 2:3:5 and their sum is 200. What is the largest number?',
    'Find the largest number using the given ratio and total.',
    'APTITUDE',
    'Ratio and Proportion',
    'MEDIUM',
    'ANALYZE',
    'Find the value represented by one ratio part.',
    'Sum = 200',
    'Ratio and total sum',
    'Largest number',
    '["80","90","100","120"]',
    '100',
    'Total ratio = 10. One part = 20. Largest number = 5 × 20 = 100.',
    '["Add all ratio terms to get total parts."]',
    '["ratio","proportion","algebra"]',
    86.0, 0, 0
),

-- =========================
-- AVERAGES
-- =========================

(
    'Average of Numbers',
    'Find the average of 10, 20, 30, 40 and 50.',
    'Calculate the arithmetic mean of the given numbers.',
    'APTITUDE',
    'Averages',
    'EASY',
    'APPLY',
    'Add all values and divide by the number of values.',
    'Five numbers are given.',
    'A list of numbers',
    'Average',
    '["20","25","30","35"]',
    '30',
    'Sum = 150. Average = 150/5 = 30.',
    '["Average = Sum / Number of values"]',
    '["average","arithmetic"]',
    96.0, 0, 0
),

(
    'Average After Adding Number',
    'The average of 5 numbers is 20. If a sixth number 30 is added, what is the new average?',
    'Calculate the new average after adding one value.',
    'APTITUDE',
    'Averages',
    'EASY',
    'APPLY',
    'First find the original total, then add the new number.',
    'Original average = 20, Original count = 5',
    'Average, count and new number',
    'New average',
    '["20","21.67","22","25"]',
    '21.67',
    'Original total = 5 × 20 = 100. New total = 130. New average = 130/6 = 21.67.',
    '["Convert the average back to total before adding the new value."]',
    '["average","arithmetic"]',
    84.0, 0, 0
),

(
    'Average of Consecutive Numbers',
    'What is the average of all integers from 1 to 99?',
    'Find the average of a sequence of consecutive integers.',
    'APTITUDE',
    'Averages',
    'EASY',
    'APPLY',
    'For consecutive numbers, average is the mean of the first and last values.',
    'Numbers range from 1 to 99.',
    'First and last number',
    'Average',
    '["49","50","51","52"]',
    '50',
    'Average = (1 + 99)/2 = 50.',
    '["For equally spaced consecutive numbers, use (first + last)/2."]',
    '["average","number-series"]',
    94.0, 0, 0
),

(
    'Average Marks',
    'A student scores 70, 80, 75 and 85 in four subjects. What score is needed in the fifth subject to obtain an average of 80?',
    'Find the missing score required to reach the target average.',
    'APTITUDE',
    'Averages',
    'MEDIUM',
    'ANALYZE',
    'Find the required total and subtract the current total.',
    'Target average = 80',
    'Existing marks and target average',
    'Required fifth score',
    '["80","85","90","95"]',
    '90',
    'Required total = 5 × 80 = 400. Current total = 310. Required score = 90.',
    '["Required total = target average × total subjects."]',
    '["average","marks","arithmetic"]',
    82.0, 0, 0
),

(
    'Average Speed Basic',
    'A car travels 60 km in 2 hours and another 40 km in 1 hour. What is its average speed for the entire journey?',
    'Calculate average speed using total distance divided by total time.',
    'APTITUDE',
    'Averages',
    'MEDIUM',
    'ANALYZE',
    'Average speed is not the simple average of the two speeds unless times are equal.',
    'Total journey consists of two parts.',
    'Distances and times',
    'Average speed',
    '["30 km/h","33.33 km/h","40 km/h","50 km/h"]',
    '33.33 km/h',
    'Total distance = 100 km. Total time = 3 hours. Average speed = 100/3 = 33.33 km/h.',
    '["Average speed = Total distance / Total time"]',
    '["average","speed","arithmetic"]',
    78.0, 0, 0
),

-- =========================
-- TIME AND WORK
-- =========================

(
    'Single Person Work',
    'A can complete a job in 10 days. What fraction of the work does A complete in one day?',
    'Find the one-day work rate of A.',
    'APTITUDE',
    'Time and Work',
    'EASY',
    'UNDERSTAND',
    'If a person completes a job in D days, their one-day work is 1/D.',
    'A completes the work in 10 days.',
    'Number of days',
    'One-day work',
    '["1/5","1/10","1/20","10"]',
    '1/10',
    'If the whole work is 1, then A completes 1/10 of the work each day.',
    '["One-day work = 1 / total days."]',
    '["time-and-work","work-rate"]',
    95.0, 0, 0
),

(
    'Two People Working Together',
    'A can complete a job in 10 days and B can complete it in 15 days. How long will they take together?',
    'Find the combined time when two people work simultaneously.',
    'APTITUDE',
    'Time and Work',
    'MEDIUM',
    'ANALYZE',
    'Add their individual one-day work rates.',
    'A = 10 days, B = 15 days',
    'Individual work times',
    'Combined time',
    '["5 days","6 days","7.5 days","8 days"]',
    '6 days',
    'Combined rate = 1/10 + 1/15 = 1/6. Therefore they finish the work in 6 days.',
    '["Add work rates, not the number of days."]',
    '["time-and-work","work-rate"]',
    86.0, 0, 0
),

(
    'Work Rate Comparison',
    'A can complete a job in 12 days while B can complete it in 18 days. Who is more efficient?',
    'Compare the work rates of two workers.',
    'APTITUDE',
    'Time and Work',
    'EASY',
    'UNDERSTAND',
    'The person who takes fewer days has the higher work rate.',
    'A = 12 days, B = 18 days',
    'Work completion times',
    'More efficient worker',
    '["A","B","Both","Cannot determine"]',
    'A',
    'A completes the job in fewer days, so A has the higher daily work rate.',
    '["Lower completion time means higher efficiency."]',
    '["time-and-work","efficiency"]',
    94.0, 0, 0
),

(
    'Work Done in Days',
    'A worker completes 1/8 of a job each day. How many days are required to complete the whole job?',
    'Find the total time from the daily work rate.',
    'APTITUDE',
    'Time and Work',
    'EASY',
    'APPLY',
    'The reciprocal of the daily work fraction gives the total days.',
    'Daily work = 1/8',
    'Daily work rate',
    'Number of days',
    '["6","8","10","12"]',
    '8',
    'If 1/8 of the work is completed each day, 8 days are required for the whole work.',
    '["Total days = 1 / one-day work."]',
    '["time-and-work","fractions"]',
    96.0, 0, 0
),

(
    'Three People Work Together',
    'A can finish a job in 12 days, B in 18 days and C in 36 days. How many days will they take working together?',
    'Calculate the combined work rate of three workers.',
    'APTITUDE',
    'Time and Work',
    'MEDIUM',
    'ANALYZE',
    'Add all three one-day work rates.',
    'A = 12 days, B = 18 days, C = 36 days',
    'Individual work times',
    'Combined time',
    '["4 days","5 days","6 days","8 days"]',
    '6 days',
    'Combined rate = 1/12 + 1/18 + 1/36 = 6/36 = 1/6. Therefore time = 6 days.',
    '["Find the LCM of the individual times to add work rates easily."]',
    '["time-and-work","lcm","work-rate"]',
    79.0, 0, 0
);
-- =====================================================
-- APTITUDE BATCH 2 — TIME, INTEREST, AGES, PIPES
-- =====================================================

INSERT IGNORE INTO aptitude_questions
(
    title,
    question_text,
    problem_statement,
    question_type,
    category,
    difficulty_level,
    blooms_level,
    description,
    constraints,
    input_format,
    output_format,
    options,
    correct_answer,
    explanation,
    hints,
    tags,
    acceptance_rate,
    total_attempts,
    total_correct
)
VALUES

-- =========================
-- TIME, SPEED AND DISTANCE
-- =========================

(
    'Basic Speed Calculation',
    'A car travels 240 km in 4 hours. What is its average speed?',
    'Calculate the average speed of the car.',
    'APTITUDE',
    'Time Speed and Distance',
    'EASY',
    'APPLY',
    'Use the formula speed = distance / time.',
    'Distance = 240 km, Time = 4 hours',
    'Distance and time',
    'Speed in km/h',
    '["40 km/h","50 km/h","60 km/h","80 km/h"]',
    '60 km/h',
    'Speed = 240 / 4 = 60 km/h.',
    '["Speed = Distance ÷ Time"]',
    '["speed","distance","time"]',
    95.0, 0, 0
),

(
    'Distance from Speed and Time',
    'A train travels at 80 km/h for 3 hours. How far does it travel?',
    'Calculate the distance covered by the train.',
    'APTITUDE',
    'Time Speed and Distance',
    'EASY',
    'APPLY',
    'Use distance = speed × time.',
    'Speed = 80 km/h, Time = 3 hours',
    'Speed and time',
    'Distance in km',
    '["200","220","240","260"]',
    '240',
    'Distance = 80 × 3 = 240 km.',
    '["Distance = Speed × Time"]',
    '["speed","distance","time"]',
    94.0, 0, 0
),

(
    'Time Required for Journey',
    'A bus travels 300 km at a speed of 60 km/h. How much time does it take?',
    'Find the travel time using distance and speed.',
    'APTITUDE',
    'Time Speed and Distance',
    'EASY',
    'APPLY',
    'Use time = distance / speed.',
    'Distance = 300 km, Speed = 60 km/h',
    'Distance and speed',
    'Time in hours',
    '["4","5","6","7"]',
    '5 hours',
    'Time = 300 / 60 = 5 hours.',
    '["Time = Distance ÷ Speed"]',
    '["speed","distance","time"]',
    93.0, 0, 0
),

(
    'Relative Speed Opposite Direction',
    'Two trains travel in opposite directions at 60 km/h and 40 km/h. What is their relative speed?',
    'Find the relative speed when two objects move in opposite directions.',
    'APTITUDE',
    'Time Speed and Distance',
    'MEDIUM',
    'ANALYZE',
    'For opposite directions, add the two speeds.',
    'Speeds = 60 km/h and 40 km/h',
    'Two speeds',
    'Relative speed',
    '["20 km/h","40 km/h","80 km/h","100 km/h"]',
    '100 km/h',
    'Relative speed = 60 + 40 = 100 km/h.',
    '["Opposite direction → add speeds."]',
    '["relative-speed","trains"]',
    87.0, 0, 0
),

(
    'Relative Speed Same Direction',
    'Two cars travel in the same direction at 75 km/h and 55 km/h. What is their relative speed?',
    'Find the relative speed when two objects move in the same direction.',
    'APTITUDE',
    'Time Speed and Distance',
    'EASY',
    'APPLY',
    'For the same direction, subtract the smaller speed from the larger speed.',
    'Speeds = 75 km/h and 55 km/h',
    'Two speeds',
    'Relative speed',
    '["10 km/h","20 km/h","30 km/h","130 km/h"]',
    '20 km/h',
    'Relative speed = 75 - 55 = 20 km/h.',
    '["Same direction → subtract speeds."]',
    '["relative-speed","speed"]',
    91.0, 0, 0
),

-- =========================
-- SIMPLE INTEREST
-- =========================

(
    'Simple Interest Basic',
    'Find the simple interest on 5000 at 8% per annum for 2 years.',
    'Calculate simple interest using the standard formula.',
    'APTITUDE',
    'Simple Interest',
    'EASY',
    'APPLY',
    'Use SI = P × R × T / 100.',
    'P = 5000, R = 8%, T = 2 years',
    'Principal, rate and time',
    'Simple interest',
    '["600","700","800","900"]',
    '800',
    'SI = 5000 × 8 × 2 / 100 = 800.',
    '["SI = PRT/100"]',
    '["simple-interest","interest"]',
    94.0, 0, 0
),

(
    'Simple Interest Amount',
    'A sum of 4000 is invested at 10% simple interest for 3 years. What is the total amount?',
    'Find the amount after adding simple interest to the principal.',
    'APTITUDE',
    'Simple Interest',
    'EASY',
    'APPLY',
    'Calculate interest first and then add it to the principal.',
    'P = 4000, R = 10%, T = 3 years',
    'Principal, rate and time',
    'Total amount',
    '["5000","5200","5400","5600"]',
    '5200',
    'SI = 4000 × 10 × 3 / 100 = 1200. Amount = 4000 + 1200 = 5200.',
    '["Amount = Principal + Simple Interest"]',
    '["simple-interest","amount"]',
    92.0, 0, 0
),

(
    'Find Principal from Simple Interest',
    'The simple interest on a sum at 5% per annum for 4 years is 1000. Find the principal.',
    'Determine the principal when interest, rate and time are known.',
    'APTITUDE',
    'Simple Interest',
    'MEDIUM',
    'ANALYZE',
    'Rearrange the simple interest formula.',
    'SI = 1000, R = 5%, T = 4 years',
    'Interest, rate and time',
    'Principal',
    '["4000","4500","5000","5500"]',
    '5000',
    'P = SI × 100 / (R × T) = 1000 × 100 / 20 = 5000.',
    '["P = SI × 100 / (R × T)"]',
    '["simple-interest","principal"]',
    81.0, 0, 0
),

(
    'Find Rate of Simple Interest',
    'A principal of 6000 earns a simple interest of 1440 in 4 years. What is the annual rate?',
    'Find the rate using the simple interest formula.',
    'APTITUDE',
    'Simple Interest',
    'MEDIUM',
    'ANALYZE',
    'Rearrange SI = PRT/100 to find R.',
    'P = 6000, SI = 1440, T = 4',
    'Principal, interest and time',
    'Annual interest rate',
    '["4%","5%","6%","8%"]',
    '6%',
    'R = 1440 × 100 / (6000 × 4) = 6%.',
    '["R = SI × 100 / (P × T)"]',
    '["simple-interest","rate"]',
    83.0, 0, 0
),

(
    'Simple Interest Time',
    'At 10% simple interest, how many years will it take for 2000 to earn 600 interest?',
    'Find the time required to earn the given simple interest.',
    'APTITUDE',
    'Simple Interest',
    'MEDIUM',
    'ANALYZE',
    'Rearrange the simple interest formula to find time.',
    'P = 2000, R = 10%, SI = 600',
    'Principal, rate and interest',
    'Time in years',
    '["2","3","4","5"]',
    '3 years',
    'T = SI × 100 / (P × R) = 600 × 100 / 20000 = 3 years.',
    '["T = SI × 100 / (P × R)"]',
    '["simple-interest","time"]',
    85.0, 0, 0
),

-- =========================
-- COMPOUND INTEREST
-- =========================

(
    'Compound Interest Basic',
    'Find the compound interest on 10000 at 10% per annum for 2 years, compounded annually.',
    'Calculate compound interest for two years.',
    'APTITUDE',
    'Compound Interest',
    'EASY',
    'APPLY',
    'Use Amount = P(1 + R/100)^T.',
    'P = 10000, R = 10%, T = 2',
    'Principal, rate and time',
    'Compound interest',
    '["2000","2100","2200","2300"]',
    '2100',
    'Amount = 10000 × 1.1² = 12100. CI = 12100 - 10000 = 2100.',
    '["Calculate the final amount first."]',
    '["compound-interest","interest"]',
    88.0, 0, 0
),

(
    'Compound Interest Amount',
    'What is the amount obtained when 5000 is invested at 20% compound interest for 2 years?',
    'Find the final amount after two years of annual compounding.',
    'APTITUDE',
    'Compound Interest',
    'EASY',
    'APPLY',
    'Apply the compound growth factor twice.',
    'P = 5000, R = 20%, T = 2',
    'Principal, rate and time',
    'Final amount',
    '["6800","7000","7200","7400"]',
    '7200',
    'Amount = 5000 × 1.2² = 7200.',
    '["Amount = P(1 + R/100)^T"]',
    '["compound-interest","amount"]',
    86.0, 0, 0
),

(
    'Compound Interest Difference',
    'Find the difference between compound interest and simple interest on 10000 at 10% for 2 years.',
    'Calculate CI and SI and find their difference.',
    'APTITUDE',
    'Compound Interest',
    'MEDIUM',
    'ANALYZE',
    'For two years, the difference can also be calculated using P(R/100)^2.',
    'P = 10000, R = 10%, T = 2',
    'Principal, rate and time',
    'Difference',
    '["50","100","150","200"]',
    '100',
    'SI = 2000 and CI = 2100. Difference = 100.',
    '["Calculate both interests or use the two-year difference formula."]',
    '["compound-interest","simple-interest"]',
    82.0, 0, 0
),

(
    'Compound Growth',
    'A population of 20000 grows by 5% annually. What will it become after 2 years?',
    'Calculate the population after two successive 5% increases.',
    'APTITUDE',
    'Compound Interest',
    'MEDIUM',
    'ANALYZE',
    'Population growth follows compound growth.',
    'Initial population = 20000',
    'Initial population and growth rate',
    'Final population',
    '["22000","22050","22500","23000"]',
    '22050',
    'Final = 20000 × 1.05² = 22050.',
    '["Successive percentage growth is compounded."]',
    '["compound-growth","percentage"]',
    79.0, 0, 0
),

(
    'Half Yearly Compound Interest',
    'A sum is compounded half-yearly at 10% per annum. What rate should be used for each half-year?',
    'Convert the annual rate into the rate applicable to each half-year.',
    'APTITUDE',
    'Compound Interest',
    'EASY',
    'UNDERSTAND',
    'For half-yearly compounding, divide the annual rate by two.',
    'Annual rate = 10%',
    'Annual interest rate',
    'Half-yearly rate',
    '["2%","5%","10%","20%"]',
    '5%',
    'Half-yearly rate = 10% / 2 = 5%.',
    '["Divide annual rate by the number of compounding periods per year."]',
    '["compound-interest","half-yearly"]',
    91.0, 0, 0
),

-- =========================
-- AGES
-- =========================

(
    'Present Age from Ratio',
    'The ages of A and B are in the ratio 3:5. If A is 18 years old, what is B’s age?',
    'Use the age ratio to determine B’s age.',
    'APTITUDE',
    'Ages',
    'EASY',
    'APPLY',
    'Find the value of one ratio part.',
    'Age ratio = 3:5, A = 18',
    'Age ratio and known age',
    'B age',
    '["25","30","35","40"]',
    '30',
    '3 parts = 18, so one part = 6. B = 5 × 6 = 30.',
    '["Divide the known age by its ratio value."]',
    '["ages","ratio"]',
    93.0, 0, 0
),

(
    'Age Difference',
    'A is 8 years older than B. If B is 20 years old, what is A’s age?',
    'Find the older person’s age using the age difference.',
    'APTITUDE',
    'Ages',
    'EASY',
    'APPLY',
    'Add the age difference to B’s age.',
    'B = 20, Difference = 8',
    'Known age and age difference',
    'A age',
    '["26","28","30","32"]',
    '28',
    'A = 20 + 8 = 28 years.',
    '["Older age = younger age + difference."]',
    '["ages","difference"]',
    96.0, 0, 0
),

(
    'Age After Years',
    'A person is 24 years old. How old will the person be after 7 years?',
    'Calculate the future age.',
    'APTITUDE',
    'Ages',
    'EASY',
    'APPLY',
    'Add the number of future years.',
    'Current age = 24',
    'Current age and years',
    'Future age',
    '["29","30","31","32"]',
    '31',
    'Future age = 24 + 7 = 31.',
    '["Future age = Present age + number of years."]',
    '["ages","future-age"]',
    97.0, 0, 0
),

(
    'Age Before Years',
    'A person is 35 years old. What was the person’s age 9 years ago?',
    'Calculate the past age.',
    'APTITUDE',
    'Ages',
    'EASY',
    'APPLY',
    'Subtract the number of past years from the present age.',
    'Current age = 35',
    'Current age and years',
    'Past age',
    '["24","25","26","27"]',
    '26',
    'Past age = 35 - 9 = 26.',
    '["Past age = Present age - number of years."]',
    '["ages","past-age"]',
    97.0, 0, 0
),

(
    'Age Ratio After Years',
    'The present ages of A and B are 20 and 30. After how many years will their ages be in the ratio 3:4?',
    'Find the number of years after which the given age ratio occurs.',
    'APTITUDE',
    'Ages',
    'MEDIUM',
    'ANALYZE',
    'Let x be the number of years and form an equation using the ratio.',
    'A = 20, B = 30',
    'Two present ages',
    'Number of years',
    '["5","10","15","20"]',
    '10',
    'After x years, (20+x)/(30+x)=3/4. Solving gives x=10.',
    '["Set up (20+x)/(30+x) = 3/4."]',
    '["ages","ratio","algebra"]',
    74.0, 0, 0
),

-- =========================
-- PIPES AND CISTERNS
-- =========================

(
    'Single Pipe Filling Tank',
    'A pipe can fill a tank in 8 hours. What fraction of the tank does it fill in one hour?',
    'Find the hourly work rate of the pipe.',
    'APTITUDE',
    'Pipes and Cisterns',
    'EASY',
    'UNDERSTAND',
    'If a pipe fills a tank in T hours, its one-hour rate is 1/T.',
    'Tank filling time = 8 hours',
    'Filling time',
    'One-hour filling fraction',
    '["1/4","1/6","1/8","1/10"]',
    '1/8',
    'The pipe fills the entire tank in 8 hours, so it fills 1/8 each hour.',
    '["One-hour work = 1 / total hours."]',
    '["pipes","work-rate"]',
    95.0, 0, 0
),

(
    'Two Pipes Filling Tank',
    'Pipe A fills a tank in 6 hours and Pipe B fills it in 3 hours. How long will they take together?',
    'Find the combined filling time.',
    'APTITUDE',
    'Pipes and Cisterns',
    'MEDIUM',
    'ANALYZE',
    'Add the filling rates of both pipes.',
    'A = 6 hours, B = 3 hours',
    'Individual filling times',
    'Combined time',
    '["1.5 hours","2 hours","2.5 hours","3 hours"]',
    '2 hours',
    'Combined rate = 1/6 + 1/3 = 1/2. Therefore the tank fills in 2 hours.',
    '["Add rates, not times."]',
    '["pipes","work-rate","fractions"]',
    88.0, 0, 0
),

(
    'Pipe and Drain',
    'A pipe fills a tank in 4 hours and a drain empties it in 12 hours. How long will the tank take to fill when both are open?',
    'Calculate the net filling rate.',
    'APTITUDE',
    'Pipes and Cisterns',
    'MEDIUM',
    'ANALYZE',
    'Subtract the drain rate from the filling pipe rate.',
    'Fill = 4 hours, Drain = 12 hours',
    'Filling and emptying times',
    'Net filling time',
    '["4 hours","6 hours","8 hours","12 hours"]',
    '6 hours',
    'Net rate = 1/4 - 1/12 = 2/12 = 1/6. Therefore time = 6 hours.',
    '["Drain rate reduces the filling rate."]',
    '["pipes","cisterns","work-rate"]',
    79.0, 0, 0
),

(
    'Three Pipes Filling Tank',
    'Three pipes can fill a tank in 12, 18 and 36 hours respectively. How long will they take together?',
    'Calculate the combined filling rate of three pipes.',
    'APTITUDE',
    'Pipes and Cisterns',
    'MEDIUM',
    'ANALYZE',
    'Add all three filling rates.',
    'Pipe times = 12, 18 and 36 hours',
    'Individual filling times',
    'Combined time',
    '["4 hours","6 hours","8 hours","9 hours"]',
    '6 hours',
    'Combined rate = 1/12 + 1/18 + 1/36 = 1/6. Therefore time = 6 hours.',
    '["Find the LCM to add the fractions easily."]',
    '["pipes","cisterns","lcm"]',
    76.0, 0, 0
),

(
    'Partial Tank Filling',
    'A pipe fills 1/5 of a tank in one hour. How much of the tank will it fill in 3 hours?',
    'Find the total fraction filled after three hours.',
    'APTITUDE',
    'Pipes and Cisterns',
    'EASY',
    'APPLY',
    'Multiply the hourly filling rate by the number of hours.',
    'Hourly rate = 1/5',
    'Filling rate and time',
    'Fraction filled',
    '["2/5","3/5","4/5","1"]',
    '3/5',
    'Filled amount = 3 × 1/5 = 3/5.',
    '["Work done = Rate × Time."]',
    '["pipes","fractions","work-rate"]',
    94.0, 0, 0
);
-- =====================================================
-- APTITUDE BATCH 3 — NUMBER SYSTEM, LCM/HCF,
-- MIXTURES, PERMUTATION/COMBINATION, PROBABILITY
-- =====================================================

INSERT IGNORE INTO aptitude_questions
(
    title,
    question_text,
    problem_statement,
    question_type,
    category,
    difficulty_level,
    blooms_level,
    description,
    constraints,
    input_format,
    output_format,
    options,
    correct_answer,
    explanation,
    hints,
    tags,
    acceptance_rate,
    total_attempts,
    total_correct
)
VALUES

-- =========================
-- NUMBER SYSTEM
-- =========================

(
    'Divisibility by 3',
    'Which of the following numbers is divisible by 3?',
    'Determine divisibility by checking the sum of the digits.',
    'APTITUDE',
    'Number System',
    'EASY',
    'APPLY',
    'A number is divisible by 3 if the sum of its digits is divisible by 3.',
    'Positive integers are given.',
    'A list of integers',
    'The number divisible by 3',
    '["124","235","351","457"]',
    '351',
    '3 + 5 + 1 = 9, and 9 is divisible by 3.',
    '["Add the digits and check whether the sum is divisible by 3."]',
    '["number-system","divisibility"]',
    93.0, 0, 0
),

(
    'Divisibility by 11',
    'Which number is divisible by 11?',
    'Use the divisibility rule for 11 to identify the correct number.',
    'APTITUDE',
    'Number System',
    'EASY',
    'APPLY',
    'For divisibility by 11, the difference between alternating digit sums must be divisible by 11.',
    'Positive integers are given.',
    'A list of integers',
    'The number divisible by 11',
    '["121","123","125","127"]',
    '121',
    'For 121, (1 + 1) - 2 = 0, so it is divisible by 11.',
    '["Calculate alternating digit sums."]',
    '["number-system","divisibility"]',
    91.0, 0, 0
),

(
    'Remainder When Divided',
    'What is the remainder when 157 is divided by 12?',
    'Find the remainder after integer division.',
    'APTITUDE',
    'Number System',
    'EASY',
    'APPLY',
    'Use division to identify the remainder.',
    '157 is a positive integer.',
    'Dividend and divisor',
    'Remainder',
    '["1","5","7","9"]',
    '1',
    '12 × 13 = 156, so the remainder is 157 - 156 = 1.',
    '["Find the largest multiple of 12 less than or equal to 157."]',
    '["number-system","remainders"]',
    96.0, 0, 0
),

(
    'Units Digit of Power',
    'What is the units digit of 7^4?',
    'Determine the last digit of the given power.',
    'APTITUDE',
    'Number System',
    'EASY',
    'ANALYZE',
    'Use the repeating cycle of units digits.',
    'Exponent is a positive integer.',
    'Base and exponent',
    'Units digit',
    '["1","3","7","9"]',
    '1',
    'Powers of 7 have units digits 7, 9, 3, 1 in a cycle of 4. Since 4 mod 4 = 0, the units digit is 1.',
    '["Look for the repeating cycle of the last digit."]',
    '["number-system","powers","units-digit"]',
    87.0, 0, 0
),

(
    'Sum of First Natural Numbers',
    'What is the sum of the first 50 natural numbers?',
    'Calculate the sum from 1 through 50.',
    'APTITUDE',
    'Number System',
    'EASY',
    'APPLY',
    'Use the formula n(n+1)/2.',
    'n = 50',
    'A positive integer n',
    'Sum of first n natural numbers',
    '["1225","1250","1275","1300"]',
    '1275',
    '50 × 51 / 2 = 1275.',
    '["Use n(n+1)/2."]',
    '["number-system","series","formula"]',
    95.0, 0, 0
),

-- =========================
-- LCM AND HCF
-- =========================

(
    'HCF of Two Numbers',
    'Find the HCF of 36 and 48.',
    'Determine the greatest common divisor of the two numbers.',
    'APTITUDE',
    'LCM and HCF',
    'EASY',
    'APPLY',
    'Find the largest number that divides both values.',
    'Both numbers are positive integers.',
    'Two integers',
    'HCF',
    '["6","8","12","16"]',
    '12',
    'The common factors include 1, 2, 3, 4, 6 and 12. The greatest is 12.',
    '["Find the common factors or use Euclidean algorithm."]',
    '["hcf","gcd","number-system"]',
    94.0, 0, 0
),

(
    'LCM of Two Numbers',
    'Find the LCM of 12 and 18.',
    'Determine the smallest positive number divisible by both values.',
    'APTITUDE',
    'LCM and HCF',
    'EASY',
    'APPLY',
    'Use prime factorization or the HCF-LCM relationship.',
    'Both numbers are positive integers.',
    'Two integers',
    'LCM',
    '["24","30","36","48"]',
    '36',
    'Multiples of 12 and 18 first meet at 36.',
    '["List multiples or use LCM × HCF = product of two numbers."]',
    '["lcm","hcf","number-system"]',
    93.0, 0, 0
),

(
    'HCF and LCM Relationship',
    'The HCF of two numbers is 6 and their LCM is 180. If one number is 30, find the other.',
    'Use the relationship between HCF, LCM and the product of two numbers.',
    'APTITUDE',
    'LCM and HCF',
    'MEDIUM',
    'ANALYZE',
    'Use HCF × LCM = product of the two numbers.',
    'HCF = 6, LCM = 180, first number = 30',
    'HCF, LCM and one number',
    'Second number',
    '["24","30","36","40"]',
    '36',
    'Second number = (6 × 180) / 30 = 36.',
    '["HCF × LCM = First number × Second number."]',
    '["lcm","hcf","algebra"]',
    81.0, 0, 0
),

(
    'LCM of Three Numbers',
    'Find the LCM of 4, 6 and 8.',
    'Find the smallest number divisible by all three values.',
    'APTITUDE',
    'LCM and HCF',
    'EASY',
    'APPLY',
    'Use prime factorization.',
    'Positive integers 4, 6 and 8.',
    'Three integers',
    'LCM',
    '["12","18","24","32"]',
    '24',
    '4 = 2², 6 = 2×3, 8 = 2³. LCM = 2³×3 = 24.',
    '["Take the highest power of every prime factor."]',
    '["lcm","prime-factorization"]',
    91.0, 0, 0
),

(
    'HCF of Three Numbers',
    'Find the HCF of 24, 36 and 60.',
    'Find the greatest number that divides all three numbers.',
    'APTITUDE',
    'LCM and HCF',
    'EASY',
    'APPLY',
    'Find the common factors of all three values.',
    'Positive integers are given.',
    'Three integers',
    'HCF',
    '["4","6","8","12"]',
    '12',
    '12 divides 24, 36 and 60, and no larger common divisor exists.',
    '["Find the HCF of the first two and then with the third."]',
    '["hcf","gcd"]',
    89.0, 0, 0
),

-- =========================
-- MIXTURES AND ALLEGATIONS
-- =========================

(
    'Simple Mixture Ratio',
    'A mixture contains milk and water in the ratio 3:2. If the total mixture is 25 litres, how much milk is present?',
    'Find the quantity of milk using the given ratio.',
    'APTITUDE',
    'Mixtures and Allegations',
    'EASY',
    'APPLY',
    'Divide the total quantity according to the ratio.',
    'Total mixture = 25 litres.',
    'Total quantity and ratio',
    'Quantity of milk',
    '["10 L","12 L","15 L","18 L"]',
    '15 L',
    'Total parts = 5. One part = 25/5 = 5 L. Milk = 3×5 = 15 L.',
    '["Add ratio parts and find the value of one part."]',
    '["mixture","ratio"]',
    92.0, 0, 0
),

(
    'Milk and Water Replacement',
    'A vessel contains 20 litres of milk. If 5 litres are replaced with water, what fraction of the vessel is milk now?',
    'Find the remaining milk after removing and replacing part of the mixture.',
    'APTITUDE',
    'Mixtures and Allegations',
    'MEDIUM',
    'ANALYZE',
    'The replacement removes 5 litres of milk and adds 5 litres of water.',
    'Initial milk = 20 L, Removed = 5 L',
    'Initial quantity and removed quantity',
    'Fraction of milk remaining',
    '["1/2","3/4","4/5","5/6"]',
    '3/4',
    'Milk remaining = 20 - 5 = 15 L. Total remains 20 L. Fraction = 15/20 = 3/4.',
    '["Track the quantity of milk left after removal."]',
    '["mixture","replacement","fractions"]',
    78.0, 0, 0
),

(
    'Average Price Mixture',
    'Rice costing 40 per kg is mixed with rice costing 60 per kg in equal quantities. What is the average price per kg?',
    'Find the cost per kilogram of the mixture.',
    'APTITUDE',
    'Mixtures and Allegations',
    'EASY',
    'APPLY',
    'For equal quantities, take the arithmetic average of the prices.',
    'Equal quantities are mixed.',
    'Two prices',
    'Average price',
    '["45","50","55","60"]',
    '50',
    'Average price = (40 + 60)/2 = 50 per kg.',
    '["Equal quantities → simple average."]',
    '["mixture","average","price"]',
    94.0, 0, 0
),

(
    'Alligation Basic',
    'Rice costing 30 per kg is mixed with rice costing 50 per kg to obtain a mixture costing 40 per kg. In what ratio should they be mixed?',
    'Find the ratio of cheaper rice to expensive rice.',
    'APTITUDE',
    'Mixtures and Allegations',
    'MEDIUM',
    'ANALYZE',
    'Use the allegation method based on differences from the mean price.',
    'Prices are 30, 40 and 50 per kg.',
    'Two prices and mean price',
    'Mixing ratio',
    '["1:1","1:2","2:1","3:2"]',
    '1:1',
    'Differences are 40-30 = 10 and 50-40 = 10, so the ratio is 1:1.',
    '["Compare each price with the mean price."]',
    '["mixture","alligation","ratio"]',
    84.0, 0, 0
),

(
    'Three Ingredient Mixture',
    'A mixture contains 2 litres of A, 3 litres of B and 5 litres of C. What percentage of the mixture is C?',
    'Find the percentage contribution of ingredient C.',
    'APTITUDE',
    'Mixtures and Allegations',
    'EASY',
    'APPLY',
    'Divide the quantity of C by the total quantity and multiply by 100.',
    'Quantities are positive.',
    'Three quantities',
    'Percentage of C',
    '["40%","50%","60%","70%"]',
    '50%',
    'Total = 2 + 3 + 5 = 10 L. C = 5 L. Percentage = 5/10 × 100 = 50%.',
    '["First calculate the total quantity."]',
    '["mixture","percentage"]',
    91.0, 0, 0
),

-- =========================
-- PERMUTATION AND COMBINATION
-- =========================

(
    'Arrange Three Letters',
    'How many ways can the letters A, B and C be arranged?',
    'Calculate the number of permutations of three distinct objects.',
    'APTITUDE',
    'Permutation and Combination',
    'EASY',
    'APPLY',
    'Use 3! for arranging three distinct objects.',
    'Three distinct letters.',
    'Number of distinct objects',
    'Number of arrangements',
    '["3","6","9","12"]',
    '6',
    '3! = 3 × 2 × 1 = 6.',
    '["For n distinct objects, arrangements = n!."]',
    '["permutation","factorial"]',
    96.0, 0, 0
),

(
    'Select Two Students',
    'From 5 students, how many different pairs can be selected?',
    'Calculate the number of combinations of 5 objects taken 2 at a time.',
    'APTITUDE',
    'Permutation and Combination',
    'EASY',
    'APPLY',
    'Order does not matter when selecting a pair.',
    'n = 5, r = 2',
    'Number of objects and selection size',
    'Number of pairs',
    '["5","10","15","20"]',
    '10',
    '5C2 = 5!/(2!3!) = 10.',
    '["Use combinations when order does not matter."]',
    '["combination","selection"]',
    94.0, 0, 0
),

(
    'Arrange Four People',
    'In how many ways can 4 people stand in a line?',
    'Find the number of linear arrangements of four distinct people.',
    'APTITUDE',
    'Permutation and Combination',
    'EASY',
    'APPLY',
    'Use factorial because order matters.',
    'Four distinct people.',
    'Number of people',
    'Number of arrangements',
    '["12","16","24","32"]',
    '24',
    '4! = 4 × 3 × 2 × 1 = 24.',
    '["Linear arrangement of n distinct objects = n!."]',
    '["permutation","factorial"]',
    95.0, 0, 0
),

(
    'Choose Committee',
    'A committee of 3 people is selected from 8 people. How many committees are possible?',
    'Find the number of ways to choose 3 people when order does not matter.',
    'APTITUDE',
    'Permutation and Combination',
    'MEDIUM',
    'APPLY',
    'Use the combination formula.',
    'n = 8, r = 3',
    'Number of people and committee size',
    'Number of committees',
    '["32","48","56","64"]',
    '56',
    '8C3 = 8!/(3!5!) = 56.',
    '["Committee selection uses combinations because order does not matter."]',
    '["combination","committee"]',
    87.0, 0, 0
),

(
    'Permutation of Two from Five',
    'How many ways can 2 different positions be filled from 5 people when order matters?',
    'Calculate the number of permutations of 5 objects taken 2 at a time.',
    'APTITUDE',
    'Permutation and Combination',
    'MEDIUM',
    'APPLY',
    'Use nPr = n!/(n-r)!.',
    'n = 5, r = 2',
    'Number of objects and positions',
    'Number of arrangements',
    '["10","15","20","25"]',
    '20',
    '5P2 = 5 × 4 = 20.',
    '["When order matters, use permutation."]',
    '["permutation","selection"]',
    89.0, 0, 0
),

-- =========================
-- PROBABILITY
-- =========================

(
    'Probability of Head',
    'A fair coin is tossed once. What is the probability of getting heads?',
    'Calculate the probability of the specified outcome.',
    'APTITUDE',
    'Probability',
    'EASY',
    'APPLY',
    'A fair coin has two equally likely outcomes.',
    'One fair coin toss.',
    'A coin toss',
    'Probability',
    '["0","1/4","1/2","1"]',
    '1/2',
    'There is one favorable outcome out of two possible outcomes.',
    '["Probability = Favorable outcomes / Total outcomes."]',
    '["probability","coin"]',
    97.0, 0, 0
),

(
    'Probability of Rolling Six',
    'A fair six-sided die is rolled once. What is the probability of getting 6?',
    'Find the probability of one specific die outcome.',
    'APTITUDE',
    'Probability',
    'EASY',
    'APPLY',
    'A fair die has six equally likely outcomes.',
    'One fair die roll.',
    'A die roll',
    'Probability',
    '["1/2","1/3","1/6","1/12"]',
    '1/6',
    'There is one favorable outcome among six possible outcomes.',
    '["One desired face out of six faces."]',
    '["probability","dice"]',
    96.0, 0, 0
),

(
    'Probability of Even Number',
    'A fair die is rolled once. What is the probability of getting an even number?',
    'Find the probability of rolling 2, 4 or 6.',
    'APTITUDE',
    'Probability',
    'EASY',
    'APPLY',
    'There are three even outcomes among six possible outcomes.',
    'One fair die roll.',
    'A die roll',
    'Probability',
    '["1/6","1/3","1/2","2/3"]',
    '1/2',
    'Favorable outcomes = 3 and total outcomes = 6. Probability = 3/6 = 1/2.',
    '["Even outcomes are 2, 4 and 6."]',
    '["probability","dice"]',
    94.0, 0, 0
),

(
    'Probability of Drawing Red Ball',
    'A bag contains 3 red balls and 2 blue balls. What is the probability of drawing a red ball?',
    'Calculate the probability of selecting a red ball.',
    'APTITUDE',
    'Probability',
    'EASY',
    'APPLY',
    'Probability is favorable red balls divided by total balls.',
    'Red = 3, Blue = 2',
    'Number of red and blue balls',
    'Probability',
    '["2/5","3/5","1/2","4/5"]',
    '3/5',
    'Total balls = 5. Red balls = 3. Probability = 3/5.',
    '["Total outcomes are all balls in the bag."]',
    '["probability","balls"]',
    95.0, 0, 0
),

(
    'Probability of At Least One Head',
    'Two fair coins are tossed. What is the probability of getting at least one head?',
    'Calculate the probability that one or both coins show heads.',
    'APTITUDE',
    'Probability',
    'MEDIUM',
    'ANALYZE',
    'Use the complement of getting no heads.',
    'Two fair coin tosses.',
    'Two coin tosses',
    'Probability',
    '["1/4","1/2","3/4","1"]',
    '3/4',
    'The only outcome with no heads is TT. Therefore probability = 1 - 1/4 = 3/4.',
    '["Use P(at least one) = 1 - P(none)."]',
    '["probability","coin","complement"]',
    86.0, 0, 0
);
-- =====================================================
-- APTITUDE BATCH 4 — DI, LOGICAL REASONING,
-- SERIES, CODING-DECODING, BLOOD RELATIONS & DIRECTIONS
-- =====================================================

INSERT IGNORE INTO aptitude_questions
(
    title,
    question_text,
    problem_statement,
    question_type,
    category,
    difficulty_level,
    blooms_level,
    description,
    constraints,
    input_format,
    output_format,
    options,
    correct_answer,
    explanation,
    hints,
    tags,
    acceptance_rate,
    total_attempts,
    total_correct
)
VALUES

-- =========================
-- DATA INTERPRETATION
-- =========================

(
    'DI Total Sales',
    'A shop sold 120, 150, 180 and 200 units from Monday to Thursday respectively. What was the total number of units sold?',
    'Calculate the total sales across the four days.',
    'APTITUDE',
    'Data Interpretation',
    'EASY',
    'APPLY',
    'Add the sales values for all four days.',
    'Four daily sales values are given.',
    'Daily sales data',
    'Total units sold',
    '["550","600","650","700"]',
    '650',
    'Total = 120 + 150 + 180 + 200 = 650.',
    '["Add all the daily values."]',
    '["data-interpretation","addition"]',
    96.0, 0, 0
),

(
    'DI Highest Sales',
    'A company sold 240, 180, 300 and 270 products in four months. In which month was the highest number of products sold?',
    'Identify the largest value in the given sales data.',
    'APTITUDE',
    'Data Interpretation',
    'EASY',
    'UNDERSTAND',
    'Compare all four monthly sales values.',
    'Four monthly sales values are given.',
    'Monthly sales data',
    'Month with highest sales',
    '["Month 1","Month 2","Month 3","Month 4"]',
    'Month 3',
    'The highest value is 300, which occurs in Month 3.',
    '["Find the maximum value."]',
    '["data-interpretation","comparison"]',
    95.0, 0, 0
),

(
    'DI Percentage Increase',
    'A company produced 800 units in January and 1000 units in February. What was the percentage increase?',
    'Calculate the percentage increase in production.',
    'APTITUDE',
    'Data Interpretation',
    'EASY',
    'APPLY',
    'Find the increase and compare it with January production.',
    'January = 800, February = 1000',
    'Two production values',
    'Percentage increase',
    '["20%","25%","30%","35%"]',
    '25%',
    'Increase = 200. Percentage increase = 200/800 × 100 = 25%.',
    '["Use January as the original value."]',
    '["data-interpretation","percentage"]',
    89.0, 0, 0
),

(
    'DI Average Sales',
    'A store records sales of 100, 120, 140, 160 and 180 units over five days. What is the average daily sales?',
    'Calculate the average of the five daily sales values.',
    'APTITUDE',
    'Data Interpretation',
    'EASY',
    'APPLY',
    'Add the five values and divide by five.',
    'Five daily sales values are given.',
    'Daily sales data',
    'Average daily sales',
    '["130","140","150","160"]',
    '140',
    'Total = 700. Average = 700/5 = 140.',
    '["Average = Total ÷ Number of days."]',
    '["data-interpretation","average"]',
    92.0, 0, 0
),

(
    'DI Ratio of Sales',
    'A company sold 240 units of Product A and 360 units of Product B. What is the ratio of A to B in simplest form?',
    'Simplify the ratio of the two sales quantities.',
    'APTITUDE',
    'Data Interpretation',
    'EASY',
    'APPLY',
    'Divide both quantities by their HCF.',
    'A = 240, B = 360',
    'Two sales values',
    'Simplified ratio',
    '["1:2","2:3","3:4","4:5"]',
    '2:3',
    'HCF of 240 and 360 is 120. Therefore 240:360 = 2:3.',
    '["Divide both values by their greatest common divisor."]',
    '["data-interpretation","ratio","hcf"]',
    91.0, 0, 0
),

-- =========================
-- LOGICAL REASONING
-- =========================

(
    'Logical Odd One Out',
    'Find the odd one out: 2, 3, 5, 7, 9.',
    'Identify the number that does not follow the common property.',
    'APTITUDE',
    'Logical Reasoning',
    'EASY',
    'ANALYZE',
    'Most numbers in the list are prime.',
    'All values are positive integers.',
    'A sequence of numbers',
    'Odd one out',
    '["2","3","7","9"]',
    '9',
    '2, 3, 5 and 7 are prime numbers, while 9 is composite.',
    '["Check whether each number is prime."]',
    '["logical-reasoning","odd-one-out","prime"]',
    94.0, 0, 0
),

(
    'Logical Statement Conclusion',
    'All cats are animals. Some animals are black. Which statement definitely follows?',
    'Determine the conclusion that is guaranteed by the statements.',
    'APTITUDE',
    'Logical Reasoning',
    'MEDIUM',
    'ANALYZE',
    'Use only the information explicitly given.',
    'Statements are assumed to be true.',
    'Statements and conclusions',
    'Valid conclusion',
    '["All cats are black","Some cats are black","All cats are animals","No cats are animals"]',
    'All cats are animals',
    'The first statement directly establishes that every cat is an animal.',
    '["Do not assume information that is not stated."]',
    '["logical-reasoning","syllogism"]',
    88.0, 0, 0
),

(
    'Logical Seating Position',
    'Five people A, B, C, D and E stand in a line. A is before B, B is before C, and D is after C. Which person must be before C?',
    'Determine the person whose position is guaranteed to be before C.',
    'APTITUDE',
    'Logical Reasoning',
    'EASY',
    'ANALYZE',
    'Use the ordering constraints directly.',
    'All five people occupy distinct positions.',
    'Ordering statements',
    'Person before C',
    '["A","D","E","Cannot determine"]',
    'A',
    'Since A is before B and B is before C, A must be before C.',
    '["Follow the chain A → B → C."]',
    '["logical-reasoning","ordering"]',
    91.0, 0, 0
),

(
    'Logical Calendar Pattern',
    'If today is Monday, what day will it be after 10 days?',
    'Determine the weekday after the given number of days.',
    'APTITUDE',
    'Logical Reasoning',
    'EASY',
    'APPLY',
    'Use the seven-day cycle.',
    'One week has 7 days.',
    'Starting day and number of days',
    'Day after given period',
    '["Wednesday","Thursday","Friday","Saturday"]',
    'Thursday',
    '10 mod 7 = 3. Three days after Monday is Thursday.',
    '["Reduce the number of days using modulo 7."]',
    '["logical-reasoning","calendar"]',
    93.0, 0, 0
),

(
    'Logical Ranking',
    'In a class, Rahul ranks 8th from the top and 13th from the bottom. How many students are in the class?',
    'Find the total number of students from the two rankings.',
    'APTITUDE',
    'Logical Reasoning',
    'EASY',
    'APPLY',
    'Add the two positions and subtract one because Rahul is counted twice.',
    'Rank from top = 8, rank from bottom = 13',
    'Two ranks',
    'Total students',
    '["19","20","21","22"]',
    '20',
    'Total = 8 + 13 - 1 = 20.',
    '["Subtract one to avoid counting Rahul twice."]',
    '["logical-reasoning","ranking"]',
    94.0, 0, 0
),

-- =========================
-- NUMBER AND LETTER SERIES
-- =========================

(
    'Number Series Addition',
    'Find the next number: 2, 5, 8, 11, ?',
    'Identify the pattern and find the next term.',
    'APTITUDE',
    'Number Series',
    'EASY',
    'ANALYZE',
    'Each term increases by 3.',
    'The sequence follows a constant difference.',
    'A number sequence',
    'Next number',
    '["12","13","14","15"]',
    '14',
    'The difference between consecutive terms is 3. Therefore 11 + 3 = 14.',
    '["Check the difference between consecutive terms."]',
    '["series","number-series"]',
    95.0, 0, 0
),

(
    'Number Series Multiplication',
    'Find the next number: 3, 6, 12, 24, ?',
    'Identify the multiplication pattern.',
    'APTITUDE',
    'Number Series',
    'EASY',
    'ANALYZE',
    'Each term is multiplied by 2.',
    'The sequence follows a constant multiplication factor.',
    'A number sequence',
    'Next number',
    '["36","42","48","54"]',
    '48',
    'Each term is twice the previous term. 24 × 2 = 48.',
    '["Check whether each term is multiplied by the same number."]',
    '["series","multiplication"]',
    96.0, 0, 0
),

(
    'Number Series Squares',
    'Find the next number: 1, 4, 9, 16, 25, ?',
    'Identify the mathematical pattern in the sequence.',
    'APTITUDE',
    'Number Series',
    'EASY',
    'ANALYZE',
    'The terms are consecutive perfect squares.',
    'Positive integer sequence.',
    'A number sequence',
    'Next number',
    '["30","32","36","49"]',
    '36',
    'The sequence is 1², 2², 3², 4², 5², so the next is 6² = 36.',
    '["Look for perfect squares."]',
    '["series","squares","number-series"]',
    94.0, 0, 0
),

(
    'Letter Series',
    'Find the next letter: A, C, E, G, ?',
    'Identify the pattern in the alphabet sequence.',
    'APTITUDE',
    'Letter Series',
    'EASY',
    'ANALYZE',
    'Every second letter of the alphabet is selected.',
    'English alphabet.',
    'A letter sequence',
    'Next letter',
    '["H","I","J","K"]',
    'I',
    'The sequence skips one letter each time: A, C, E, G, I.',
    '["Move two positions forward in the alphabet."]',
    '["series","letter-series","reasoning"]',
    93.0, 0, 0
),

(
    'Difference Series',
    'Find the next number: 5, 9, 15, 23, 33, ?',
    'Identify the pattern using differences between consecutive terms.',
    'APTITUDE',
    'Number Series',
    'MEDIUM',
    'ANALYZE',
    'The differences are 4, 6, 8 and 10.',
    'Positive integer sequence.',
    'A number sequence',
    'Next number',
    '["43","45","47","49"]',
    '45',
    'Differences increase by 2: 4, 6, 8, 10, 12. Therefore 33 + 12 = 45.',
    '["Calculate the differences between consecutive terms."]',
    '["series","difference-series"]',
    85.0, 0, 0
),

-- =========================
-- CODING-DECODING
-- =========================

(
    'Coding Letters',
    'If CAT is coded as DBU, how is DOG coded using the same pattern?',
    'Each letter is shifted one position forward in the alphabet.',
    'APTITUDE',
    'Coding Decoding',
    'EASY',
    'ANALYZE',
    'Apply the same +1 alphabet shift to every character.',
    'All letters are uppercase.',
    'A word',
    'Encoded word',
    '["EPH","EOG","DPH","FPH"]',
    'EPH',
    'D becomes E, O becomes P and G becomes H, giving EPH.',
    '["Move every letter one position forward."]',
    '["coding-decoding","alphabet"]',
    94.0, 0, 0
),

(
    'Reverse Coding',
    'If TABLE is coded as ELBAT, how is CHAIR coded using the same rule?',
    'Reverse the letters of the given word.',
    'APTITUDE',
    'Coding Decoding',
    'EASY',
    'APPLY',
    'The code is formed by reversing the original word.',
    'Words contain uppercase letters.',
    'A word',
    'Encoded word',
    '["RIAHC","RIAHC","CHAIR","RIACH"]',
    'RIAHC',
    'CHAIR reversed is RIAHC.',
    '["Write the letters from right to left."]',
    '["coding-decoding","reversal"]',
    96.0, 0, 0
),

(
    'Alphabet Position Coding',
    'If A=1, B=2, C=3 and so on, what is the code for CAT as the sum of letter positions?',
    'Convert each letter into its alphabet position and add them.',
    'APTITUDE',
    'Coding Decoding',
    'EASY',
    'APPLY',
    'Use alphabet positions for each letter.',
    'A=1 through Z=26.',
    'A word',
    'Numerical code',
    '["22","24","26","28"]',
    '24',
    'C=3, A=1, T=20. Total = 3 + 1 + 20 = 24.',
    '["Convert each letter to its alphabet number."]',
    '["coding-decoding","alphabet","numbers"]',
    92.0, 0, 0
),

(
    'Symbol Coding',
    'If in a code language + means × and × means −, what is the value of 8 + 2 × 3?',
    'Replace the symbols according to the given coding rule.',
    'APTITUDE',
    'Coding Decoding',
    'MEDIUM',
    'ANALYZE',
    'Replace + with multiplication and × with subtraction.',
    'Use standard arithmetic precedence after replacement.',
    'Expression with coded operators',
    'Calculated value',
    '["10","13","16","19"]',
    '13',
    'The expression becomes 8 × 2 − 3 = 16 − 3 = 13.',
    '["First replace each coded symbol with its actual operation."]',
    '["coding-decoding","symbols","arithmetic"]',
    81.0, 0, 0
),

(
    'Number Coding Pattern',
    'If 2 is coded as 6, 3 as 12 and 4 as 20, how is 5 coded?',
    'Identify the mathematical rule used to encode each number.',
    'APTITUDE',
    'Coding Decoding',
    'EASY',
    'ANALYZE',
    'Each number is multiplied by the next integer.',
    'Positive integers.',
    'A number',
    'Encoded number',
    '["25","30","35","40"]',
    '30',
    '2×3=6, 3×4=12, 4×5=20, so 5×6=30.',
    '["Look for n × (n+1)."]',
    '["coding-decoding","number-pattern"]',
    89.0, 0, 0
),

-- =========================
-- BLOOD RELATIONS AND DIRECTIONS
-- =========================

(
    'Basic Blood Relation',
    'Pointing to a man, Ravi says, "He is the son of my father." How is the man related to Ravi?',
    'Determine the relationship using the given family statement.',
    'APTITUDE',
    'Blood Relations',
    'EASY',
    'ANALYZE',
    'The son of Ravi’s father is Ravi himself or Ravi’s brother. Since the person is another man, he is Ravi’s brother.',
    'Assume Ravi and the person are different individuals.',
    'A family relationship statement',
    'Relationship',
    '["Father","Brother","Uncle","Cousin"]',
    'Brother',
    'The son of Ravi’s father, other than Ravi, is Ravi’s brother.',
    '["Identify the common parent first."]',
    '["blood-relations","family"]',
    92.0, 0, 0
),

(
    'Mother Relation',
    'A is the mother of B. B is the brother of C. How is A related to C?',
    'Determine the relationship between A and C.',
    'APTITUDE',
    'Blood Relations',
    'EASY',
    'UNDERSTAND',
    'If B and C are siblings, their mother is also C’s mother.',
    'All relationships are direct.',
    'Relationship statements',
    'Relationship',
    '["Sister","Mother","Aunt","Grandmother"]',
    'Mother',
    'A is B’s mother and B and C are siblings, so A is C’s mother.',
    '["Follow the parent relationship from B to C."]',
    '["blood-relations","family"]',
    96.0, 0, 0
),

(
    'Uncle Relation',
    'P is the brother of Q. Q is the mother of R. How is P related to R?',
    'Determine the relationship between P and R.',
    'APTITUDE',
    'Blood Relations',
    'EASY',
    'ANALYZE',
    'The brother of someone’s mother is the child’s maternal uncle.',
    'All relationships are direct.',
    'Relationship statements',
    'Relationship',
    '["Father","Brother","Uncle","Grandfather"]',
    'Uncle',
    'P is Q’s brother and Q is R’s mother, so P is R’s maternal uncle.',
    '["The mother’s brother is the maternal uncle."]',
    '["blood-relations","family"]',
    94.0, 0, 0
),

(
    'Direction Distance',
    'A person walks 5 km north and then 3 km east. In which direction is the person from the starting point?',
    'Determine the final direction relative to the starting position.',
    'APTITUDE',
    'Directions',
    'EASY',
    'ANALYZE',
    'North followed by east places the person in the northeast direction.',
    'Movements are perpendicular.',
    'Movement directions and distances',
    'Final direction',
    '["North","East","North-East","South-East"]',
    'North-East',
    'Moving north and then east places the person northeast of the starting point.',
    '["Draw a simple coordinate diagram."]',
    '["directions","reasoning"]',
    95.0, 0, 0
),

(
    'Opposite Direction',
    'A person faces north and turns 90 degrees clockwise. Which direction is the person facing?',
    'Determine the new direction after the rotation.',
    'APTITUDE',
    'Directions',
    'EASY',
    'APPLY',
    'A clockwise 90-degree turn from north points east.',
    'Directions are based on a standard compass.',
    'Initial direction and rotation',
    'Final direction',
    '["West","East","South","North"]',
    'East',
    'Starting from north, a 90-degree clockwise turn leads to east.',
    '["Imagine a clock hand turning clockwise from north."]',
    '["directions","rotation"]',
    97.0, 0, 0
);

