package com.interviewtwin.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(
    name = "coding_submissions",
    indexes = {
        @Index(name = "idx_user_id", columnList = "user_id"),
        @Index(name = "idx_submitted_at", columnList = "submitted_at")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CodingSubmission {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long submissionId;

    /*
     * The owner is always assigned by the backend.
     * Never accept user ownership from the client.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    /*
     * The coding question is selected by the backend.
     * Never trust a client-provided question ownership relationship.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "coding_id", nullable = false)
    @JsonIgnore
    private CodingQuestion codingQuestion;

    /*
     * Submitted source code.
     *
     * The service/controller must enforce a strict maximum
     * length before creating this entity.
     */
    @Column(columnDefinition = "TEXT", nullable = false)
    private String code;

    /*
     * Keep this as String for compatibility with the existing
     * database/application. The service must whitelist supported
     * languages instead of trusting arbitrary client values.
     */
    @Builder.Default
    @Column(nullable = false, length = 50)
    private String language = "JAVA";

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private SubmissionStatus status = SubmissionStatus.PENDING;

    /*
     * Score must be validated by the service:
     * 0 <= score <= 100.
     */
    @Column(precision = 5, scale = 2)
    private BigDecimal score;

    /*
     * These fields are execution/evaluation results and should
     * be generated by the backend, never trusted from the client.
     */
    @Column(columnDefinition = "TEXT")
    private String compilationOutput;

    @Column(columnDefinition = "TEXT")
    private String testResults;

    private Integer executionTime;

    private Integer memoryUsed;

    @Column(columnDefinition = "TEXT")
    private String complexityAnalysis;

    @Builder.Default
    private Integer passedTestCases = 0;

    @Builder.Default
    private Integer totalTestCases = 0;

    /*
     * Server-controlled timestamp.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime submittedAt;

    @PrePersist
    protected void onCreate() {
        if (submittedAt == null) {
            submittedAt = LocalDateTime.now();
        }

        if (status == null) {
            status = SubmissionStatus.PENDING;
        }

        if (passedTestCases == null) {
            passedTestCases = 0;
        }

        if (totalTestCases == null) {
            totalTestCases = 0;
        }
    }

    public enum SubmissionStatus {
        ACCEPTED,
        WRONG_ANSWER,
        TIME_LIMIT_EXCEEDED,
        MEMORY_LIMIT_EXCEEDED,
        COMPILATION_ERROR,
        RUNTIME_ERROR,
        PENDING
    }
}